### PR TITLE
Added Keywords of Proteomics

### PR DESCRIPTION
**Pull request by Jiaxin2018**
Step2. crawl README.md from home_url only on Github,  match  "mass spectra OR mass spectrum OR proteome OR proteomics"  in README.md, and then check the matched projects mannually.

### CODE REVIEW

**Comment by ypriverol** [comment]
@Jiaxin2018 can you double-check why lint is failing.

**Comment by Jiaxin2018** [comment]
ok, I will try to solve the problem

**Comment by Jiaxin2018** [comment]
I have checked all the errors. They were reporting " too many spaces after colon  (colons)" and "trailing spaces  (trailing-spaces)". However, when I checked them in the annotations.yaml, I found no error as the instructions. So, I'm a little confused.

**Comment by ypriverol** [comment]
Can you check because they were working before? When I merge your previous PR everything got mess-up. It can be that the rules of lint are too stringent.

**Comment by ypriverol** [comment]
@Jiaxin2018 the PR has major conflicts with the master branch that do not allow to merge the PR.

**Pull request closed without merging**
